drop table if exists t;
create table t (a int primary key, b varchar(255), c int, key (b), key (c,b)) partition by range (a) (partition p0 values less than (1000000), partition p1M values less than (2000000));
alter table t set tiflash replica 1;
insert into t values (1,"1",-1);
analyze table t;
set @t := 1;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t;
set @t := 2 * @t;
insert into t select a+@t,a+@t,-(a+@t) from t ORDER BY a LIMIT 600000;

explain select /*+ READ_FROM_STORAGE(TIFLASH[t]) */ count(*) from t partition (p0);
select /*+ READ_FROM_STORAGE(TIFLASH[t]) */ count(*) from t partition (p0);
show warnings;
explain select /*+ READ_FROM_STORAGE(TIKV[t]) */ count(*) from t partition (p0);
select /*+ READ_FROM_STORAGE(TIKV[t]) */ count(*) from t partition (p0);
show warnings;
select * from information_schema.tiflash_replica;
select sleep(20);
select * from information_schema.tiflash_replica;
explain select /*+ READ_FROM_STORAGE(TIFLASH[t]) */ count(*) from t partition (p0);
select /*+ READ_FROM_STORAGE(TIFLASH[t]) */ count(*) from t partition (p0);
show warnings;
explain select /*+ READ_FROM_STORAGE(TIKV[t]) */ count(*) from t partition (p0);
select /*+ READ_FROM_STORAGE(TIKV[t]) */ count(*) from t partition (p0);
show warnings;

alter table t reorganize partition p0 INTO (partition p0 values less than (500000), partition p500k values less than (1000000));

select * from information_schema.tiflash_replica where table_schema = 'test';
select `database`,`table`,tidb_table,table_id,is_tombstone,segment_count,total_rows,tiflash_instance from information_schema.tiflash_tables where tidb_database = 'test';
select `database`,`table`,tidb_table,table_id,is_tombstone,segment_count,total_rows, p.table_name, p.partition_name from information_schema.tiflash_tables,information_schema.partitions p where table_id = p.tidb_partition_id;
select table_name,partition_name,tidb_partition_id from information_schema.partitions where partition_name is not null;

explain select /*+ READ_FROM_STORAGE(TIFLASH[t]) */ count(*) from t partition (p0);
select /*+ READ_FROM_STORAGE(TIFLASH[t]) */ count(*) from t partition (p0);
show warnings;
explain select /*+ READ_FROM_STORAGE(TIKV[t]) */ count(*) from t partition (p0);
select /*+ READ_FROM_STORAGE(TIKV[t]) */ count(*) from t partition (p0);
show warnings;

select * from information_schema.tiflash_replica where table_schema = 'test';
select `database`,`table`,tidb_table,table_id,is_tombstone,segment_count,total_rows,tiflash_instance from information_schema.tiflash_tables where tidb_database = 'test';
select `database`,`table`,tidb_table,table_id,is_tombstone,segment_count,total_rows, p.table_name, p.partition_name from information_schema.tiflash_tables,information_schema.partitions p where table_id = p.tidb_partition_id;
select table_name,partition_name,tidb_partition_id from information_schema.partitions where partition_name is not null;
